#' Update raster layer names and metadata
#'
#' @description
#' [update_raster_names()] updates the layer names, variable names, and long
#' names of a `SpatRaster` object. Layer names are generated by combining a
#' user-defined prefix with a daily date sequence spanning from 2012-01-01
#' to 2018-12-31.
#'
#' This function is useful when working with time-series raster stacks where
#' each layer represents a daily value and needs standardized naming and
#' metadata attributes.
#'
#' @param rast A `SpatRaster` object whose layer names and metadata will be updated.
#' @param prefix A character string used as a prefix for each raster layer name.
#'   The final layer names will be constructed as `prefix_YYYYMMDD`.
#' @param var_name A character string defining the variable name to assign to
#'   the raster via `terra::varnames()`.
#' @param long_name A character string defining the long descriptive name to
#'   assign to the raster via `terra::longnames()`.
#'
#' @returns A `SpatRaster` object with:
#'
#'  - Layer names formatted as `prefix_YYYYMMDD`
#'  - Variable name set via `terra::varnames()`
#'  - Long descriptive name set via `terra::longnames()`
#'
#' @details
#' The function internally creates a daily date sequence between
#' 2012-01-01 and 2018-12-31 using `lubridate::ymd()` and formats it as
#' `YYYYMMDD`. The length of this sequence must match the number of layers
#' in `rast`; otherwise, an error will occur when assigning names.
#'
#' @export
update_raster_names <- function(rast, prefix, var_name, long_name) {
  date_sequence <- seq(
    lubridate::ymd("20120101"),
    lubridate::ymd("20181231"),
    by = "day"
  ) |>
    format("%Y%m%d")

  names(rast) <- paste(prefix, date_sequence, sep = "_")
  varnames(rast) <- var_name
  longnames(rast) <- long_name

  rast
}
